# Leitura do Lakehouse com Pandas

Leitura direta do Parquet particionado com `pandas` + `pyarrow` — sem Spark. O pyarrow entende o particionamento Hive (`ingest_date=...`) e devolve a coluna de partição automaticamente.

In [1]:
import pandas as pd

LAKEHOUSE = "/home/jovyan/lakehouse"

## veiculos

In [2]:
SOURCE = 'veiculos'
df_raw = pd.read_parquet(f"{LAKEHOUSE}/raw/{SOURCE}", engine="pyarrow")
print(f"raw: {df_raw.shape[0]} linhas x {df_raw.shape[1]} colunas")

raw: 150 linhas x 14 colunas

In [3]:
df_raw['km_atual'] = df_raw['km_atual'].astype(int)

In [4]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   veiculo_id           150 non-null    object
 1   placa                150 non-null    object
 2   marca                150 non-null    object
 3   modelo               150 non-null    object
 4   ano_fabricacao       150 non-null    object
 5   tipo                 150 non-null    object
 6   capacidade_kg        150 non-null    object
 7   capacidade_paletes   150 non-null    object
 8   km_atual             150 non-null    int64
 9   status               150 non-null    object
 10  data_ultima_revisao  148 non-null    object
 11  source_file          150 non-null    object
 12  ingested_at          150 non-null    datetime64[ns]
 13  ingest_date          150 non-null    category
dtypes: category(1), datetime64[ns](1), int64(1), object(11)
memory usage: 15.6+ KB

In [5]:
len(df_raw['veiculo_id'].drop_duplicates())

150

In [6]:
df_raw['placa'].value_counts()

placa
INVALIDA    4
XNY3W49     1
PFX4S35     1
RHU8X37     1
NQX5T35     1
           ..
UWW3E19     1
XGE1P70     1
XEI1N69     1
HVN2M29     1
FMM4O99     1
Name: count, Length: 147, dtype: int64

In [7]:
df_raw['marca'].value_counts()

marca
Iveco            34
Mercedes-Benz    32
DAF              23
Volvo            23
MAN              21
Scania           17
Name: count, dtype: int64

In [8]:
df_raw['ano_fabricacao'].value_counts()

ano_fabricacao
2017    21
2025    19
2024    17
2018    16
2021    15
2022    15
2016    15
2023    11
2019     9
2020     9
1999     3
Name: count, dtype: int64

In [9]:
df_raw['tipo'].value_counts()

tipo
VUC                30
Carreta LS         26
Caminhão Truck     26
Caminhão Toco      24
Bitrem             24
Carreta Simples    20
Name: count, dtype: int64

In [10]:
df_raw['capacidade_paletes'].value_counts()

capacidade_paletes
3     30
30    26
14    26
8     24
37    24
25    20
Name: count, dtype: int64

In [11]:
df_raw['km_atual'].astype(int).describe()

count       150.000000
mean     412641.566667
std      255582.718145
min     -691723.000000
25%      226728.750000
50%      434282.000000
75%      645342.000000
max      798449.000000
Name: km_atual, dtype: float64

In [12]:
df_raw.query("km_atual < 0 ")

,veiculo_id,placa,marca,modelo,ano_fabricacao,tipo,capacidade_kg,capacidade_paletes,km_atual,status,data_ultima_revisao,source_file,ingested_at,ingest_date
33,VEI-0034,ETD4Z35,DAF,XF 530,2024,Caminhão Toco,14000,8,-201014,ativo,2026-04-07,/opt/airflow/data/veiculos/veiculos.csv,2026-07-06 15:48:52.408307,2026-07-06
83,VEI-0084,SHF8J94,Iveco,S-Way,2021,VUC,6500,3,-691723,ativo,2025-12-20,/opt/airflow/data/veiculos/veiculos.csv,2026-07-06 15:48:52.408307,2026-07-06

In [13]:
df_raw['status'].value_counts()

status
ativo            123
em_manutencao     16
inativo           11
Name: count, dtype: int64

In [14]:
df_raw['data_ultima_revisao'].value_counts()

data_ultima_revisao
2026-01-26    4
2026-02-24    3
2025-12-20    3
2025-12-13    2
2026-03-08    2
             ..
2025-07-19    1
2025-12-22    1
2025-11-04    1
2025-07-24    1
2026-04-01    1
Name: count, Length: 121, dtype: int64

## motoristas

In [15]:
SOURCE = 'motoristas'
df_raw = pd.read_parquet(f"{LAKEHOUSE}/raw/{SOURCE}", engine="pyarrow")
print(f"raw: {df_raw.shape[0]} linhas x {df_raw.shape[1]} colunas")

raw: 124 linhas x 13 colunas

In [16]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124 entries, 0 to 123
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   base_operacional  124 non-null    object
 1   categoria_cnh     124 non-null    object
 2   cnh               121 non-null    object
 3   cpf               124 non-null    object
 4   data_admissao     124 non-null    object
 5   motorista_id      124 non-null    object
 6   nome              124 non-null    object
 7   status            124 non-null    object
 8   telefone          121 non-null    object
 9   validade_cnh      123 non-null    object
 10  source_file       124 non-null    object
 11  ingested_at       124 non-null    datetime64[ns]
 12  ingest_date       124 non-null    category
dtypes: category(1), datetime64[ns](1), object(11)
memory usage: 12.0+ KB

In [17]:
df_raw['base_operacional'].value_counts()

base_operacional
CD São Paulo - Guarulhos               18
CD Rio de Janeiro - Duque de Caxias    17
CD Recife - Jaboatão                   16
CD Belo Horizonte - Contagem           16
CD Curitiba - CIC                      16
CD Porto Alegre - Canoas               15
CD Campinas - Sumaré                   14
CD Goiânia - Aparecida                 12
Name: count, dtype: int64

In [18]:
df_raw['categoria_cnh'].value_counts()

categoria_cnh
D    43
E    41
C    40
Name: count, dtype: int64

In [19]:
df_raw['cnh'].value_counts()

cnh
24107566541    2
79276168480    2
43317481983    2
48950112353    2
69937859375    1
              ..
57509317567    1
13316417742    1
38035638925    1
72746897690    1
91409324097    1
Name: count, Length: 117, dtype: int64

In [20]:
df_raw.query("cnh == '24107566541' ")

,base_operacional,categoria_cnh,cnh,cpf,data_admissao,motorista_id,nome,status,telefone,validade_cnh,source_file,ingested_at,ingest_date
30,CD Campinas - Sumaré,D,24107566541,798.614.052-67,2018-06-06,MOT-0031,Sr. Paulo Pinto,afastado,+55 (084) 8136-5860,2028-08-02,/opt/airflow/data/motoristas/motoristas.json,2026-07-06 15:48:51.650972,2026-07-06
122,CD Campinas - Sumaré,D,24107566541,798.614.052-67,2018-06-06,MOT-0031,SR. PAULO PINTO,afastado,+55 (084) 8136-5860,2028-08-02,/opt/airflow/data/motoristas/motoristas.json,2026-07-06 15:48:51.650972,2026-07-06

In [21]:
df_raw.query("cnh == '79276168480' ")

,base_operacional,categoria_cnh,cnh,cpf,data_admissao,motorista_id,nome,status,telefone,validade_cnh,source_file,ingested_at,ingest_date
44,CD Porto Alegre - Canoas,D,79276168480,196.425.873-19,2019-02-10,MOT-0045,Lorenzo Lopes,ativo,0800-684-1636,2028-03-19,/opt/airflow/data/motoristas/motoristas.json,2026-07-06 15:48:51.650972,2026-07-06
120,CD Porto Alegre - Canoas,D,79276168480,196.425.873-19,2019-02-10,MOT-0045,LORENZO LOPES,ativo,0800-684-1636,2028-03-19,/opt/airflow/data/motoristas/motoristas.json,2026-07-06 15:48:51.650972,2026-07-06

In [22]:
df_raw['cpf'].value_counts()

cpf
196.425.873-19    2
706.953.428-00    2
798.614.052-67    2
563.894.270-00    2
597.136.840-01    1
                 ..
420.657.839-74    1
061.732.459-06    1
689.247.013-04    1
184.279.350-05    1
827.190.346-22    1
Name: count, Length: 120, dtype: int64

In [23]:
df_raw['data_admissao'].value_counts()

data_admissao
2023-12-26    2
2018-06-06    2
2019-02-10    2
2020-08-01    2
2019-02-03    2
             ..
2025-07-06    1
2021-11-16    1
2019-09-11    1
2020-03-11    1
2019-06-07    1
Name: count, Length: 118, dtype: int64

In [24]:
df_raw['motorista_id'].value_counts()

motorista_id
MOT-0045    2
MOT-0055    2
MOT-0031    2
MOT-0073    2
MOT-0005    1
           ..
MOT-0116    1
MOT-0117    1
MOT-0118    1
MOT-0119    1
MOT-0120    1
Name: count, Length: 120, dtype: int64

In [25]:
df_raw['nome'].value_counts()

nome
                               4
Lorenzo das Neves              2
João Guilherme da Conceição    1
Nicolas Sousa                  1
Rodrigo Rezende                1
                              ..
Raul Camargo                   1
LORENZO LOPES                  1
CALEB BARBOSA                  1
SR. PAULO PINTO                1
ANNA LIZ SIQUEIRA              1
Name: count, Length: 120, dtype: int64

In [26]:
df_raw['status'].value_counts()

status
ativo        84
afastado     14
desligado    14
ferias       12
Name: count, dtype: int64

In [27]:
df_raw['telefone'].value_counts()

telefone
+55 (084) 8136-5860    2
0800-684-1636          2
(031) 8815-2718        2
+55 41 0184-7529       2
81 0878 5042           1
                      ..
+55 (021) 4308 9708    1
(031) 9172 2981        1
+55 81 5936 6883       1
+55 41 9349-7618       1
+55 61 8931-3061       1
Name: count, Length: 117, dtype: int64

In [28]:
df_raw['validade_cnh'].value_counts()

validade_cnh
2027-09-29    2
2028-03-19    2
2027-06-14    2
2028-08-02    2
2026-10-31    2
             ..
2027-01-21    1
2027-11-15    1
2028-01-30    1
2028-03-01    1
2027-12-30    1
Name: count, Length: 116, dtype: int64

## viagens

In [29]:
SOURCE = 'viagens'
df_raw = pd.read_parquet(f"{LAKEHOUSE}/raw/{SOURCE}", engine="pyarrow")
print(f"raw: {df_raw.shape[0]} linhas x {df_raw.shape[1]} colunas")

raw: 3000 linhas x 15 colunas

In [30]:
df_raw['distancia_km'] = df_raw['distancia_km'].astype(int)
df_raw['peso_carga_kg'] = df_raw['peso_carga_kg'].astype(int)

In [31]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   viagem_id            3000 non-null   object
 1   veiculo_id           3000 non-null   object
 2   motorista_id         3000 non-null   object
 3   geocerca_origem_id   3000 non-null   object
 4   geocerca_destino_id  3000 non-null   object
 5   data_inicio          2951 non-null   object
 6   data_fim_prevista    3000 non-null   object
 7   data_fim_real        1975 non-null   object
 8   status               3000 non-null   object
 9   distancia_km         3000 non-null   int64
 10  peso_carga_kg        3000 non-null   int64
 11  nota_fiscal          2953 non-null   object
 12  source_file          3000 non-null   object
 13  ingested_at          3000 non-null   datetime64[ns]
 14  ingest_date          3000 non-null   category
dtypes: category(1), datetime64[ns](1), int64(2), object(11)
memory usage: 331.3+ KB

In [32]:
df_raw['viagem_id'].value_counts()

viagem_id
VIA-000001    1
VIA-000002    1
VIA-000003    1
VIA-000004    1
VIA-000005    1
             ..
VIA-002996    1
VIA-002997    1
VIA-002998    1
VIA-002999    1
VIA-003000    1
Name: count, Length: 3000, dtype: int64

In [33]:
df_raw['veiculo_id'].value_counts()

veiculo_id
VEI-0126    32
VEI-0121    31
VEI-9999    28
VEI-0093    28
VEI-0109    28
            ..
VEI-0142    11
VEI-0148    11
VEI-0043    10
VEI-0011    10
VEI-0129     8
Name: count, Length: 151, dtype: int64

In [34]:
df_raw['motorista_id'].value_counts()

motorista_id
MOT-0031    52
MOT-0055    48
MOT-0045    47
MOT-0073    46
MOT-0030    40
            ..
MOT-0080    16
MOT-0106    15
MOT-0065    15
MOT-0101    14
MOT-0090    11
Name: count, Length: 121, dtype: int64

In [35]:
df_raw['geocerca_origem_id'].value_counts()

geocerca_origem_id
GEO-0002    388
GEO-0003    383
GEO-0005    382
GEO-0001    378
GEO-0006    372
GEO-0008    369
GEO-0004    367
GEO-0007    361
Name: count, dtype: int64

In [36]:
df_raw['geocerca_destino_id'].value_counts()

geocerca_destino_id
GEO-0021    134
GEO-0028    130
GEO-0031    128
GEO-0030    126
GEO-0037    123
GEO-0024    119
GEO-0025    116
GEO-0004    112
GEO-0026    112
GEO-0038    112
GEO-0033    111
GEO-0027    111
GEO-0036    110
GEO-0023    107
GEO-0035    107
GEO-0020    107
GEO-0029    105
GEO-0022    105
GEO-0019    104
GEO-0002     97
GEO-0008     95
GEO-0032     93
GEO-0006     92
GEO-0003     92
GEO-0007     90
GEO-0001     88
GEO-0034     88
GEO-0005     86
Name: count, dtype: int64

In [37]:
df_raw[df_raw['data_inicio'].isna()].shape[0]

49

In [38]:
df_raw[df_raw['data_fim_real'].isna()]['status'].value_counts()

status
em_transito    447
atrasada       327
cancelada      251
Name: count, dtype: int64

In [39]:
df_raw['status'].value_counts()

status
concluida      1975
em_transito     447
atrasada        327
cancelada       251
Name: count, dtype: int64

In [40]:
df_raw['distancia_km'].describe()

count    3000.000000
mean     1244.733333
std       771.749319
min     -2486.000000
25%       656.750000
50%      1269.000000
75%      1884.250000
max      2500.000000
Name: distancia_km, dtype: float64

In [41]:
df_raw.query("distancia_km < 0").shape[0]

51

In [42]:
df_raw['peso_carga_kg'].describe()

count     3000.000000
mean     19749.363333
std      11498.200583
min          0.000000
25%       9685.750000
50%      19502.000000
75%      29645.500000
max      39995.000000
Name: peso_carga_kg, dtype: float64

In [43]:
df_raw.query("peso_carga_kg == 0")

,viagem_id,veiculo_id,motorista_id,geocerca_origem_id,geocerca_destino_id,data_inicio,data_fim_prevista,data_fim_real,status,distancia_km,peso_carga_kg,nota_fiscal,source_file,ingested_at,ingest_date
114,VIA-000115,VEI-0025,MOT-0055,GEO-0008,GEO-0035,2026-04-28 21:34:58.211731,2026-04-30 02:34:58.211731,2026-04-30 09:34:58.211731,concluida,1022,0,NF-557816,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
118,VIA-000119,VEI-0080,MOT-0009,GEO-0001,GEO-0006,2026-04-28 21:38:41.500723,2026-04-30 07:38:41.500723,None,cancelada,1031,0,NF-183846,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
122,VIA-000123,VEI-0115,MOT-0076,GEO-0002,GEO-0032,2026-04-28 21:37:24.813164,2026-04-30 11:37:24.813164,2026-04-30 18:37:24.813164,concluida,2337,0,NF-231273,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
205,VIA-000206,VEI-0085,MOT-0056,GEO-0008,GEO-0028,2026-04-28 21:34:22.809180,2026-04-30 01:34:22.809180,2026-04-30 00:34:22.809180,concluida,1465,0,NF-956149,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
229,VIA-000230,VEI-0068,MOT-0089,GEO-0003,GEO-0022,2026-04-28 21:39:16.095057,2026-04-30 16:39:16.095057,2026-04-30 15:39:16.095057,concluida,2039,0,NF-345550,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
396,VIA-000397,VEI-0027,MOT-0011,GEO-0006,GEO-0003,2026-04-28 21:37:40.443009,2026-04-30 11:37:40.443009,2026-04-30 14:37:40.443009,concluida,2185,0,NF-492664,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
414,VIA-000415,VEI-0002,MOT-0010,GEO-0008,GEO-0002,2026-04-28 21:37:39.399283,2026-04-29 22:37:39.399283,2026-04-29 23:37:39.399283,concluida,209,0,NF-399262,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
479,VIA-000480,VEI-0144,MOT-0030,GEO-0004,GEO-0006,2026-04-28 21:36:46.847466,2026-04-29 09:36:46.847466,None,atrasada,158,0,NF-155971,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
653,VIA-000654,VEI-0059,MOT-0029,GEO-0008,GEO-0021,2026-04-28 21:37:25.045837,2026-05-01 06:37:25.045837,2026-05-01 12:37:25.045837,concluida,1543,0,NF-284266,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
740,VIA-000741,VEI-0042,MOT-0040,GEO-0003,GEO-0031,2026-04-28 21:36:47.488503,2026-04-29 20:36:47.488503,None,cancelada,2394,0,NF-163259,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
805,VIA-000806,VEI-0066,MOT-0069,GEO-0002,GEO-0021,2026-04-28 21:36:55.357603,2026-04-30 08:36:55.357603,None,em_transito,1514,0,NF-115103,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
1000,VIA-001001,VEI-0144,MOT-0048,GEO-0006,GEO-0020,2026-04-28 21:38:47.128232,2026-04-29 03:38:47.128232,None,cancelada,751,0,NF-445919,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
1001,VIA-001002,VEI-0122,MOT-0006,GEO-0007,GEO-0005,2026-04-28 21:37:36.003707,2026-04-29 12:37:36.003707,None,em_transito,2406,0,NF-153815,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
1162,VIA-001163,VEI-0089,MOT-0067,GEO-0007,GEO-0030,2026-04-28 21:35:04.524333,2026-05-01 18:35:04.524333,2026-05-01 21:35:04.524333,concluida,268,0,NF-957761,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
1163,VIA-001164,VEI-0016,MOT-0051,GEO-0007,GEO-0034,2026-04-28 21:35:26.320240,2026-04-29 14:35:26.320240,None,em_transito,1315,0,NF-188711,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
1191,VIA-001192,VEI-0128,MOT-0045,GEO-0001,GEO-0030,2026-04-28 21:35:33.894325,2026-04-29 19:35:33.894325,2026-04-30 01:35:33.894325,concluida,2124,0,NF-764206,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
1268,VIA-001269,VEI-0047,MOT-0091,GEO-0003,GEO-0008,2026-04-28 21:38:44.159454,2026-04-29 11:38:44.159454,2026-04-29 14:38:44.159454,concluida,1803,0,NF-266803,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
1416,VIA-001417,VEI-0016,MOT-0040,GEO-0004,GEO-0001,2026-04-28 21:33:55.737521,2026-04-30 05:33:55.737521,2026-04-30 13:33:55.737521,concluida,810,0,NF-672710,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
1432,VIA-001433,VEI-0009,MOT-0012,GEO-0008,GEO-0031,2026-04-28 21:35:08.620154,2026-05-01 21:35:08.620154,None,em_transito,982,0,NF-640685,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
1547,VIA-001548,VEI-0089,MOT-0107,GEO-0004,GEO-0021,2026-04-28 21:38:42.443574,2026-04-29 22:38:42.443574,2026-04-29 20:38:42.443574,concluida,1001,0,NF-140907,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
1784,VIA-001785,VEI-0144,MOT-0020,GEO-0001,GEO-0026,2026-04-28 21:36:06.152143,2026-05-01 11:36:06.152143,2026-05-01 16:36:06.152143,concluida,1486,0,NF-592871,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
1935,VIA-001936,VEI-0062,MOT-0102,GEO-0005,GEO-0023,2026-04-28 21:37:12.056104,2026-04-29 02:37:12.056104,2026-04-29 02:37:12.056104,concluida,-1500,0,NF-738434,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
2094,VIA-002095,VEI-0037,MOT-0087,GEO-0006,GEO-0025,2026-04-28 21:34:02.182888,2026-04-29 17:34:02.182888,2026-04-29 18:34:02.182888,concluida,200,0,NF-666629,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
2184,VIA-002185,VEI-0003,MOT-0045,GEO-0001,GEO-0002,2026-04-28 21:38:18.265077,2026-04-30 15:38:18.265077,2026-04-30 13:38:18.265077,concluida,953,0,NF-241581,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
2213,VIA-002214,VEI-0134,MOT-0066,GEO-0001,GEO-0024,2026-04-28 21:35:58.646873,2026-04-30 04:35:58.646873,2026-04-30 08:35:58.646873,concluida,-739,0,NF-290435,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
2291,VIA-002292,VEI-0044,MOT-0079,GEO-0001,GEO-0006,2026-04-28 21:34:00.091979,2026-04-30 07:34:00.091979,None,cancelada,2233,0,NF-579747,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
2433,VIA-002434,VEI-0079,MOT-0061,GEO-0003,GEO-0029,2026-04-28 21:36:07.321785,2026-04-30 13:36:07.321785,2026-04-30 19:36:07.321785,concluida,234,0,NF-745669,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
2479,VIA-002480,VEI-0126,MOT-0043,GEO-0005,GEO-0003,2026-04-28 21:37:15.767341,2026-04-30 17:37:15.767341,2026-05-01 00:37:15.767341,concluida,1917,0,NF-635847,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
2750,VIA-002751,VEI-0113,MOT-0033,GEO-0003,GEO-0031,2026-04-28 21:35:49.209524,2026-04-30 17:35:49.209524,2026-04-30 18:35:49.209524,concluida,525,0,NF-415821,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
2860,VIA-002861,VEI-0023,MOT-0110,GEO-0004,GEO-0037,2026-04-28 21:37:36.714529,2026-05-01 13:37:36.714529,2026-05-01 19:37:36.714529,concluida,1205,0,NF-413576,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
2933,VIA-002934,VEI-0054,MOT-9999,GEO-0001,GEO-0007,2026-04-28 21:36:06.206789,2026-05-01 08:36:06.206789,2026-05-01 07:36:06.206789,concluida,2263,0,NF-687875,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06

In [44]:
df_raw['nota_fiscal'].value_counts()

nota_fiscal
NF-352576    2
NF-248944    2
NF-212159    1
NF-872064    1
NF-146444    1
            ..
NF-633171    1
NF-945051    1
NF-372343    1
NF-369145    1
NF-378521    1
Name: count, Length: 2951, dtype: int64

In [45]:
df_raw.query("nota_fiscal == 'NF-352576'")

,viagem_id,veiculo_id,motorista_id,geocerca_origem_id,geocerca_destino_id,data_inicio,data_fim_prevista,data_fim_real,status,distancia_km,peso_carga_kg,nota_fiscal,source_file,ingested_at,ingest_date
778,VIA-000779,VEI-0074,MOT-0092,GEO-0004,GEO-0025,2026-04-28 21:34:18.701751,2026-04-29 04:34:18.701751,2026-04-29 11:34:18.701751,concluida,1384,38224,NF-352576,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06
1291,VIA-001292,VEI-0016,MOT-0111,GEO-0002,GEO-0024,2026-04-28 21:38:40.315809,2026-04-30 22:38:40.315809,2026-05-01 06:38:40.315809,concluida,1609,38009,NF-352576,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,2026-07-06

In [46]:
df_staging = pd.read_parquet(f"{LAKEHOUSE}/staging/{SOURCE}", engine="pyarrow")

In [47]:
df_staging

,viagem_id,veiculo_id,motorista_id,geocerca_origem_id,geocerca_destino_id,data_inicio,data_fim_prevista,data_fim_real,status,distancia_km,peso_carga_kg,nota_fiscal,source_file,ingested_at,dq_observations,quality_ok,processed_at,ingest_date
0,VIA-002921,VEI-0094,MOT-0086,GEO-0008,GEO-0036,2026-04-28 21:33:47.180722,2026-05-01 11:33:47.180722,NaT,ATRASADA,1321,17335,NF-100503,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,,True,2026-07-06 15:49:24.746941,2026-07-06
1,VIA-002358,VEI-0035,MOT-0017,GEO-0004,GEO-0023,2026-04-28 21:39:01.842560,2026-05-01 04:39:01.842560,2026-05-01 12:39:01.842560,CONCLUIDA,1502,19788,NF-101449,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,,True,2026-07-06 15:49:24.746941,2026-07-06
2,VIA-002935,VEI-9999,MOT-0096,GEO-0004,GEO-0027,2026-04-28 21:37:19.619938,2026-04-30 15:37:19.619938,NaT,EM_TRANSITO,147,39682,NF-101506,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,,True,2026-07-06 15:49:24.746941,2026-07-06
3,VIA-002819,VEI-0118,MOT-0025,GEO-0006,GEO-0021,2026-04-28 21:37:05.581952,2026-04-29 09:37:05.581952,2026-04-29 07:37:05.581952,CONCLUIDA,1402,28765,NF-101754,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,,True,2026-07-06 15:49:24.746941,2026-07-06
4,VIA-002188,VEI-0033,MOT-0015,GEO-0003,GEO-0023,2026-04-28 21:38:26.731606,2026-05-01 08:38:26.731606,2026-05-01 08:38:26.731606,CONCLUIDA,99,15181,NF-101878,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,,True,2026-07-06 15:49:24.746941,2026-07-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2847,VIA-001129,VEI-0098,MOT-0021,GEO-0007,GEO-0024,2026-04-28 21:33:50.880617,2026-04-30 09:33:50.880617,2026-04-30 12:33:50.880617,CONCLUIDA,1701,24800,NF-997744,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,,True,2026-07-06 15:49:24.746941,2026-07-06
2848,VIA-002820,VEI-0137,MOT-0091,GEO-0008,GEO-0031,2026-04-28 21:38:31.519793,2026-05-01 21:38:31.519793,2026-05-02 01:38:31.519793,CONCLUIDA,2461,31291,NF-997774,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,,True,2026-07-06 15:49:24.746941,2026-07-06
2849,VIA-000907,VEI-0048,MOT-0022,GEO-0001,GEO-0027,2026-04-28 21:35:28.307377,2026-04-29 11:35:28.307377,NaT,EM_TRANSITO,2321,11986,NF-997801,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,,True,2026-07-06 15:49:24.746941,2026-07-06
2850,VIA-002859,VEI-9999,MOT-0014,GEO-0007,GEO-0035,2026-04-28 21:38:39.161606,2026-04-29 09:38:39.161606,NaT,ATRASADA,794,27133,NF-998094,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,,True,2026-07-06 15:49:24.746941,2026-07-06
2851,VIA-000413,VEI-0053,MOT-0115,GEO-0005,GEO-0034,2026-04-28 21:38:18.411146,2026-04-30 23:38:18.411146,2026-05-01 07:38:18.411146,CONCLUIDA,610,38601,NF-999133,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,,True,2026-07-06 15:49:24.746941,2026-07-06

In [48]:
df_staging.query("nota_fiscal == 'NF-352576'")

,viagem_id,veiculo_id,motorista_id,geocerca_origem_id,geocerca_destino_id,data_inicio,data_fim_prevista,data_fim_real,status,distancia_km,peso_carga_kg,nota_fiscal,source_file,ingested_at,dq_observations,quality_ok,processed_at,ingest_date
800,VIA-000779,VEI-0074,MOT-0092,GEO-0004,GEO-0025,2026-04-28 21:34:18.701751,2026-04-29 04:34:18.701751,2026-04-29 11:34:18.701751,CONCLUIDA,1384,38224,NF-352576,/opt/airflow/data/viagens/viagens.csv,2026-07-06 15:48:52.311988,,True,2026-07-06 15:49:24.746941,2026-07-06

## posicoes

In [49]:
SOURCE = 'posicoes'
df_raw = pd.read_parquet(f"{LAKEHOUSE}/raw/{SOURCE}", engine="pyarrow")
print(f"raw: {df_raw.shape[0]} linhas x {df_raw.shape[1]} colunas")

raw: 56182 linhas x 12 colunas

In [50]:
df_raw['velocidade_kmh'] = df_raw['velocidade_kmh'].astype(int)

In [51]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56182 entries, 0 to 56181
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   posicao_id       56182 non-null  object
 1   viagem_id        56182 non-null  object
 2   veiculo_id       56182 non-null  object
 3   latitude         56182 non-null  float64
 4   longitude        56182 non-null  float64
 5   timestamp        55766 non-null  object
 6   velocidade_kmh   56182 non-null  int64
 7   ignicao          56182 non-null  bool
 8   odometro_metros  56182 non-null  float64
 9   source_file      56182 non-null  object
 10  ingested_at      56182 non-null  datetime64[ns]
 11  ingest_date      56182 non-null  category
dtypes: bool(1), category(1), datetime64[ns](1), float64(3), int64(1), object(5)
memory usage: 4.4+ MB

In [52]:
df_raw['velocidade_kmh'].describe()

count    56182.000000
mean        59.443202
std         73.680582
min        -10.000000
25%         27.000000
50%         55.000000
75%         83.000000
max        999.000000
Name: velocidade_kmh, dtype: float64

In [53]:
df_raw.query("velocidade_kmh > 110")

,posicao_id,viagem_id,veiculo_id,latitude,longitude,timestamp,velocidade_kmh,ignicao,odometro_metros,source_file,ingested_at,ingest_date
5,POS-CE078E75B9,VIA-000003,VEI-0116,-13.116507,-39.398622,2026-04-28 22:29:58.588212,999,True,460500.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
35,POS-D29E4C3BE6,VIA-000004,VEI-0086,-18.160992,-47.748149,2026-04-29 06:00:13.170904,999,True,492667.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
421,POS-0B516415AA,VIA-000024,VEI-0106,-8.137312,-35.057272,2026-04-28 21:56:47.645519,999,True,22667.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
765,POS-28C18B0B0C,VIA-000042,VEI-0069,-20.658283,-44.709545,2026-04-29 01:03:46.479184,999,True,1828318.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
1070,POS-E533183ADA,VIA-000056,VEI-0148,-21.116917,-44.579177,2026-04-29 03:53:27.232193,999,True,1031333.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
...,...,...,...,...,...,...,...,...,...,...,...,...
55125,POS-82AC5C2D77,VIA-002724,VEI-0120,-20.130365,-45.921102,2026-04-29 00:54:21.187248,999,True,101111.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
55920,POS-C366074052,VIA-002762,VEI-0039,-19.199531,-48.233178,2026-04-28 23:24:32.161414,999,True,244263.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
56006,POS-8C7A0488DE,VIA-002766,VEI-0045,-24.126678,-48.037969,2026-04-28 22:41:55.470032,999,True,406400.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
56014,POS-6386342926,VIA-002766,VEI-0045,-26.586237,-49.627409,2026-04-29 00:45:55.470032,999,True,1219200.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
56145,POS-BBFC59AE50,VIA-002772,VEI-0097,-27.673744,-49.362152,2026-04-29 02:35:09.796667,999,True,62963.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06

In [54]:
df_raw.query("velocidade_kmh < 0")

,posicao_id,viagem_id,veiculo_id,latitude,longitude,timestamp,velocidade_kmh,ignicao,odometro_metros,source_file,ingested_at,ingest_date
171,POS-5626543A3D,VIA-000010,VEI-0026,-8.007360,-34.827612,2026-04-29 05:41:47.174684,-10,True,421000.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
194,POS-7310A107D4,VIA-000012,VEI-0131,-8.085068,-34.973490,2026-04-28 21:36:21.043288,-10,True,0.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
206,POS-F5ADE37AA5,VIA-000012,VEI-0131,-5.962211,-45.672164,2026-04-29 01:12:21.043288,-10,True,894857.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
239,POS-C24F9AEF38,VIA-000014,VEI-0129,-20.322936,-43.603316,2026-04-29 05:02:49.234886,-10,True,236800.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
290,POS-7BC3BE8046,VIA-000017,VEI-0127,-27.687180,-49.927945,2026-04-28 23:41:25.377510,-10,True,294062.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
...,...,...,...,...,...,...,...,...,...,...,...,...
55070,POS-B98BBFA1E6,VIA-002721,VEI-0135,-16.780993,-41.395921,2026-04-29 00:34:17.013837,-10,True,896400.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
55191,POS-54A4DFCA24,VIA-002727,VEI-0131,-26.129577,-49.127105,2026-04-29 00:43:35.101400,-10,True,204412.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
55497,POS-31D52DFCFC,VIA-002741,VEI-0097,-19.308888,-48.425591,2026-04-28 23:03:40.412746,-10,True,156000.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
55725,POS-9EB9720F7E,VIA-002752,VEI-0037,-19.959502,-44.076081,2026-04-28 21:37:12.816422,-10,True,0.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
55790,POS-527BCB66CF,VIA-002756,VEI-0150,-22.344925,-48.971016,2026-04-29 00:24:15.215040,-10,True,121176.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06

In [55]:
df_raw['ignicao'].value_counts()

ignicao
True     55673
False      509
Name: count, dtype: int64

In [56]:
df_raw.query("viagem_id == 'VIA-000115'")

,posicao_id,viagem_id,veiculo_id,latitude,longitude,timestamp,velocidade_kmh,ignicao,odometro_metros,source_file,ingested_at,ingest_date
2229,POS-09CA9DEC81,VIA-000115,VEI-0025,-8.077885,-35.005084,2026-04-28 21:34:58.211731,54,True,0.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2230,POS-71BF9DDB76,VIA-000115,VEI-0025,-8.921272,-35.571618,2026-04-28 21:52:58.211731,50,True,51100.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2231,POS-7B980E1473,VIA-000115,VEI-0025,-9.699655,-36.133549,2026-04-28 22:52:58.211731,4,True,102200.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2232,POS-7A17B31534,VIA-000115,VEI-0025,-10.446664,-36.732046,2026-04-28 22:46:58.211731,64,True,153300.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2233,POS-1B12D88DA6,VIA-000115,VEI-0025,-11.320337,-37.240651,2026-04-28 23:10:58.211731,96,True,204400.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2234,POS-22C2638705,VIA-000115,VEI-0025,-12.070049,-37.848168,2026-04-28 22:49:58.211731,97,True,255500.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2235,POS-AA87F1B204,VIA-000115,VEI-0025,-12.868097,-38.409221,2026-04-28 23:04:58.211731,79,True,306600.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2236,POS-54B1CC35D6,VIA-000115,VEI-0025,-13.684034,-38.984630,2026-04-29 00:36:58.211731,71,True,357700.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2237,POS-B120CA2445,VIA-000115,VEI-0025,-14.475582,-39.571351,2026-04-28 22:54:58.211731,7,True,408800.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2238,POS-0809F8B8D3,VIA-000115,VEI-0025,-15.262072,-40.072765,2026-04-29 01:19:58.211731,60,True,459900.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2239,POS-84C6E0A109,VIA-000115,VEI-0025,-15.983882,-40.668881,2026-04-28 23:34:58.211731,91,True,511000.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2240,POS-6D5C3E851F,VIA-000115,VEI-0025,-16.784720,-41.283055,2026-04-29 03:59:58.211731,34,True,562100.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2241,POS-B15680F14B,VIA-000115,VEI-0025,-17.590816,-41.772443,2026-04-29 04:46:58.211731,27,True,613200.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2242,POS-2AAD7D5754,VIA-000115,VEI-0025,-18.363785,-42.373642,2026-04-29 05:48:58.211731,70,True,664300.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2243,POS-855D79E3F4,VIA-000115,VEI-0025,-19.175014,-42.947622,2026-04-29 06:12:58.211731,999,False,715400.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2244,POS-B8A8037302,VIA-000115,VEI-0025,-19.990309,-43.464962,2026-04-29 06:04:58.211731,109,True,766500.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2245,POS-5ACC7EA103,VIA-000115,VEI-0025,-20.824082,-44.114448,2026-04-29 07:10:58.211731,108,True,817600.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2246,POS-C8250E8CC2,VIA-000115,VEI-0025,-21.580735,-44.603576,2026-04-29 00:24:58.211731,57,True,868700.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2247,POS-83DAE3917B,VIA-000115,VEI-0025,-22.358020,-45.230097,2026-04-29 08:58:58.211731,59,True,919800.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2248,POS-9B48F57BF8,VIA-000115,VEI-0025,-23.187490,-45.724660,2026-04-29 03:35:58.211731,85,True,970900.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06
2249,POS-6904A2E673,VIA-000115,VEI-0025,-23.922101,-46.343051,2026-04-29 03:54:58.211731,78,True,1022000.0,/opt/airflow/data/rastreamento/posicoes.parquet,2026-07-06 15:48:52.100502,2026-07-06

## geocercas

In [57]:
SOURCE = 'geocercas'
df_raw = pd.read_parquet(f"{LAKEHOUSE}/raw/{SOURCE}", engine="pyarrow")
print(f"raw: {df_raw.shape[0]} linhas x {df_raw.shape[1]} colunas")

raw: 38 linhas x 6 colunas

In [58]:
df_raw['type'].value_counts()

type
Feature    38
Name: count, dtype: int64

In [59]:
df_raw

,geometry,properties,type,source_file,ingested_at,ingest_date
0,"{'coordinates': [[['-46.4731' '-23.426617'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0001', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
1,"{'coordinates': [[['-49.3588' '-25.486017'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0002', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
2,"{'coordinates': [[['-43.3117' '-22.776617'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0003', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
3,"{'coordinates': [[['-44.0539' '-19.923017'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0004', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
4,"{'coordinates': [[['-51.1744' '-29.908517'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0005', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
5,"{'coordinates': [[['-47.2669' '-22.811917'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0006', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
6,"{'coordinates': [[['-49.244' '-16.741017'], ['...","{'ativo': 'true', 'geocerca_id': 'GEO-0007', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
7,"{'coordinates': [[['-35.0206' '-8.103817'], ['...","{'ativo': 'true', 'geocerca_id': 'GEO-0008', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
8,"{'coordinates': [[['-45.884' '-23.186305'], ['...","{'ativo': 'true', 'geocerca_id': 'GEO-0009', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
9,"{'coordinates': [[['-47.02' '-23.472305'], ['-...","{'ativo': 'true', 'geocerca_id': 'GEO-0010', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
10,"{'coordinates': [[['-48.84' '-24.312305'], ['-...","{'ativo': 'true', 'geocerca_id': 'GEO-0011', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
11,"{'coordinates': [[['-49.65' '-25.857305'], ['-...","{'ativo': 'true', 'geocerca_id': 'GEO-0012', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
12,"{'coordinates': [[['-47.13' '-22.977305'], ['-...","{'ativo': 'true', 'geocerca_id': 'GEO-0013', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
13,"{'coordinates': [[['-45.7' '-23.048203'], ['-4...","{'ativo': 'true', 'geocerca_id': 'GEO-0014', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
14,"{'coordinates': [[['-47.48' '-23.318203'], ['-...","{'ativo': 'true', 'geocerca_id': 'GEO-0015', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
15,"{'coordinates': [[['-48.5' '-24.148203'], ['-4...","{'ativo': 'true', 'geocerca_id': 'GEO-0016', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
16,"{'coordinates': [[['-49.4' '-25.598203'], ['-4...","{'ativo': 'true', 'geocerca_id': 'GEO-0017', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
17,"{'coordinates': [[['-46.95' '-23.098203'], ['-...","{'ativo': 'true', 'geocerca_id': 'GEO-0018', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
18,"{'coordinates': [[['-46.6333' '-23.546008'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0019', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
19,"{'coordinates': [[['-60.0217' '-3.114508'], ['...","{'ativo': 'true', 'geocerca_id': 'GEO-0020', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
20,"{'coordinates': [[['-48.548' '-27.590908'], ['...","{'ativo': 'true', 'geocerca_id': 'GEO-0021', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
21,"{'coordinates': [[['-43.1729' '-22.902308'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0022', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
22,"{'coordinates': [[['-47.9292' '-15.775608'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0023', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
23,"{'coordinates': [[['-51.1696' '-23.300008'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0024', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
24,"{'coordinates': [[['-43.9345' '-19.912208'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0025', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
25,"{'coordinates': [[['-34.877' '-8.043108'], ['-...","{'ativo': 'true', 'geocerca_id': 'GEO-0026', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
26,"{'coordinates': [[['-48.8487' '-26.299908'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0027', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
27,"{'coordinates': [[['-43.5034' '-20.385008'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0028', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
28,"{'coordinates': [[['-46.3322' '-23.957308'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0029', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
29,"{'coordinates': [[['-47.3331' '-22.745108'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0030', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
30,"{'coordinates': [[['-47.8208' '-21.172208'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0031', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
31,"{'coordinates': [[['-52.3783' '-24.040008'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0032', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
32,"{'coordinates': [[['-52.4065' '-28.257408'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0033', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
33,"{'coordinates': [[['-51.1794' '-29.164008'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0034', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
34,"{'coordinates': [[['-46.3267' '-23.949508'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0035', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
35,"{'coordinates': [[['-59.99' '-3.065508'], ['-5...","{'ativo': 'true', 'geocerca_id': 'GEO-0036', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
36,"{'coordinates': [[['-38.5124' '-12.966908'], [...","{'ativo': 'true', 'geocerca_id': 'GEO-0037', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06
37,"{'coordinates': [[['-49.255' '-16.675408'], ['...","{'ativo': 'true', 'geocerca_id': 'GEO-0038', '...",Feature,/opt/airflow/data/geocercas/geocercas.geojson,2026-07-06 15:48:52.161289,2026-07-06